function Jx_f = Jx_f(X,Y,Z,tx,tz,wx,wy,wz)
%JX_F
%    JX_F = JX_F(X,Y,Z,TX,TZ,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:12

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5;
t7 = sqrt(t5);
t8 = 1.0./t7;
t9 = cos(t7);
t10 = sin(t7);
t11 = t9-1.0;
t12 = t8.*t10.*wy;
t13 = t6.*t11.*wx.*wz;
Jx_f = (tx-Y.*(t8.*t10.*wz+t6.*t11.*wx.*wy)+Z.*(t12-t13)+X.*(t6.*t11.*(t3+t4)+1.0))./(tz+Y.*(t8.*t10.*wx-t6.*t11.*wy.*wz)+Z.*(t6.*t11.*(t2+t3)+1.0)-X.*(t12+t13));
