function Jx_tx = Jx_tx(X,Y,Z,f,tz,wx,wy,wz)
%JX_TX
%    JX_TX = JX_TX(X,Y,Z,F,TZ,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:12

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5;
t7 = sqrt(t5);
t8 = 1.0./t7;
t9 = cos(t7);
t10 = sin(t7);
t11 = t9-1.0;
Jx_tx = f./(tz-X.*(t8.*t10.*wy+t6.*t11.*wx.*wz)+Y.*(t8.*t10.*wx-t6.*t11.*wy.*wz)+Z.*(t6.*t11.*(t2+t3)+1.0));
