function Jx_tz = Jx_tz(X,Y,Z,f,tx,tz,u0,wx,wy,wz)
%JX_TZ
%    JX_TZ = JX_TZ(X,Y,Z,F,TX,TZ,U0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:12

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t4+t5;
t7 = 1.0./t6;
t8 = sqrt(t6);
t9 = 1.0./t8;
t10 = cos(t8);
t11 = sin(t8);
t12 = t10-1.0;
t13 = t9.*t11.*wx;
t14 = t9.*t11.*wy;
t15 = t7.*t12.*wx.*wz;
t16 = t7.*t12.*wy.*wz;
t18 = t5.*t7.*t12;
t17 = -t16;
t19 = t18+1.0;
t21 = t14+t15;
t20 = Z.*t19;
t22 = X.*t21;
t23 = t13+t17;
t24 = -t22;
t25 = Y.*t23;
t26 = t20+t24+t25+tz;
Jx_tz = -1.0./t26.^2.*(-X.*(t21.*u0-f.*(t7.*t12.*(t3+t4)+1.0))+f.*tx+tz.*u0-Y.*(f.*(t9.*t11.*wz+t7.*t12.*wx.*wy)-t23.*u0)+Z.*(t19.*u0+f.*(t14-t15)))+u0./t26;
