function Jx_X = Jx_X(X,Y,Z,f,tx,tz,u0,wx,wy,wz)
%JX_X
%    JX_X = JX_X(X,Y,Z,F,TX,TZ,U0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:12

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t3+t4;
t7 = t4+t5;
t8 = 1.0./t7;
t9 = sqrt(t7);
t10 = 1.0./t9;
t11 = cos(t9);
t12 = sin(t9);
t13 = t11-1.0;
t14 = t10.*t12.*wx;
t15 = t10.*t12.*wy;
t16 = t8.*t13.*wx.*wz;
t17 = t8.*t13.*wy.*wz;
t19 = t5.*t8.*t13;
t20 = t6.*t8.*t13;
t18 = -t17;
t21 = t19+1.0;
t22 = t20+1.0;
t26 = t15+t16;
t23 = Z.*t21;
t24 = f.*t22;
t27 = X.*t26;
t28 = t26.*u0;
t29 = t14+t18;
t25 = -t24;
t30 = -t27;
t31 = Y.*t29;
t32 = t25+t28;
t33 = t23+t30+t31+tz;
Jx_X = (t24-t28)./t33+t26.*1.0./t33.^2.*(f.*tx+tz.*u0+X.*(t24-t28)-Y.*(f.*(t10.*t12.*wz+t8.*t13.*wx.*wy)-t29.*u0)+Z.*(t21.*u0+f.*(t15-t16)));
