function Jx_Y = Jx_Y(X,Y,Z,f,tx,tz,u0,wx,wy,wz)
%JX_Y
%    JX_Y = JX_Y(X,Y,Z,F,TX,TZ,U0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:12

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t4+t5;
t7 = 1.0./t6;
t8 = sqrt(t6);
t9 = 1.0./t8;
t10 = cos(t8);
t11 = sin(t8);
t12 = t10-1.0;
t13 = t9.*t11.*wx;
t14 = t9.*t11.*wy;
t15 = t9.*t11.*wz;
t16 = t7.*t12.*wx.*wy;
t17 = t7.*t12.*wx.*wz;
t18 = t7.*t12.*wy.*wz;
t20 = t5.*t7.*t12;
t19 = -t18;
t21 = t20+1.0;
t23 = t14+t17;
t24 = t15+t16;
t22 = Z.*t21;
t25 = X.*t23;
t26 = f.*t24;
t27 = t13+t19;
t28 = -t25;
t29 = Y.*t27;
t30 = t27.*u0;
t31 = -t30;
t33 = t22+t28+t29+tz;
t32 = t26+t31;
Jx_Y = -t32./t33-t27.*1.0./t33.^2.*(-X.*(t23.*u0-f.*(t7.*t12.*(t3+t4)+1.0))-Y.*t32+f.*tx+tz.*u0+Z.*(t21.*u0+f.*(t14-t17)));
