function Jx_Z = Jx_Z(X,Y,Z,f,tx,tz,u0,wx,wy,wz)
%JX_Z
%    JX_Z = JX_Z(X,Y,Z,F,TX,TZ,U0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:13

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t4+t5;
t7 = 1.0./t6;
t8 = sqrt(t6);
t9 = 1.0./t8;
t10 = cos(t8);
t11 = sin(t8);
t12 = t10-1.0;
t13 = t9.*t11.*wx;
t14 = t9.*t11.*wy;
t15 = t7.*t12.*wx.*wz;
t16 = t7.*t12.*wy.*wz;
t19 = t5.*t7.*t12;
t17 = -t15;
t18 = -t16;
t20 = t19+1.0;
t23 = t14+t15;
t21 = Z.*t20;
t22 = t20.*u0;
t24 = X.*t23;
t25 = t13+t18;
t26 = t14+t17;
t27 = -t24;
t28 = Y.*t25;
t29 = f.*t26;
t30 = t22+t29;
t31 = t21+t27+t28+tz;
Jx_Z = t30./t31-t20.*1.0./t31.^2.*(-X.*(t23.*u0-f.*(t7.*t12.*(t3+t4)+1.0))+Z.*t30+f.*tx+tz.*u0-Y.*(f.*(t9.*t11.*wz+t7.*t12.*wx.*wy)-t25.*u0));
