function Jy_f = Jy_f(X,Y,Z,ty,tz,wx,wy,wz)
%JY_F
%    JY_F = JY_F(X,Y,Z,TY,TZ,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:14

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5;
t7 = sqrt(t5);
t8 = 1.0./t7;
t9 = cos(t7);
t10 = sin(t7);
t11 = t9-1.0;
t12 = t8.*t10.*wx;
t13 = t6.*t11.*wy.*wz;
Jy_f = (ty-Z.*(t12+t13)+X.*(t8.*t10.*wz-t6.*t11.*wx.*wy)+Y.*(t6.*t11.*(t2+t4)+1.0))./(tz-X.*(t8.*t10.*wy+t6.*t11.*wx.*wz)+Y.*(t12-t13)+Z.*(t6.*t11.*(t2+t3)+1.0));
