function Jy_wz = Jy_wz(X,Y,Z,f,ty,tz,v0,wx,wy,wz)
%JY_WZ
%    JY_WZ = JY_WZ(X,Y,Z,F,TY,TZ,V0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:13

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t2+t4;
t7 = t4+t5;
t8 = 1.0./t7;
t10 = sqrt(t7);
t9 = t8.^2;
t11 = 1.0./t10;
t13 = cos(t10);
t14 = sin(t10);
t12 = t11.^3;
t15 = t13-1.0;
t16 = t8.*t13.*wx.*wz;
t17 = t8.*t13.*wy.*wz;
t18 = t11.*t14.*wx;
t19 = t11.*t14.*wy;
t20 = t8.*t15.*wx;
t21 = t8.*t15.*wy;
t22 = -t17;
t23 = t12.*t14.*wx.*wz;
t24 = t12.*t14.*wy.*wz;
t30 = t4.*t12.*t14.*wx;
t31 = t4.*t12.*t14.*wy;
t33 = t4.*t9.*t15.*wx.*2.0;
t34 = t4.*t9.*t15.*wy.*2.0;
t35 = t5.*t8.*t15;
t36 = t5.*t12.*t14.*wz;
t38 = t5.*t9.*t15.*wz.*2.0;
t25 = t20.*wz;
t26 = t21.*wz;
t27 = -t20;
t28 = -t21;
t29 = -t23;
t37 = t35+1.0;
t45 = t36+t38;
t32 = -t26;
t39 = Z.*t37;
t40 = t19+t25;
t46 = t22+t24+t27+t30+t33;
t47 = t16+t28+t29+t31+t34;
t41 = X.*t40;
t42 = t18+t32;
t43 = -t41;
t44 = Y.*t42;
t48 = t39+t43+t44+tz;
Jy_wz = (-Z.*(t45.*v0-f.*(-t16+t23+t28+t31+t34))+X.*(t46.*v0+f.*(t11.*t14+t23.*wy+t4.*t8.*t13-t4.*t12.*t14+t9.*t15.*wx.*wy.*wz.*2.0))+Y.*(t47.*v0-f.*(t8.*t15.*wz.*-2.0+t6.*t9.*t15.*wz.*2.0+t6.*t12.*t14.*wz)))./t48-1.0./t48.^2.*(X.*t46+Y.*t47-Z.*t45).*(f.*ty+Y.*(t42.*v0+f.*(t6.*t8.*t15+1.0))+tz.*v0-Z.*(f.*(t18+t26)-t37.*v0)-X.*(f.*(t20.*wy-t11.*t14.*wz)+t40.*v0));
