function Jy_X = Jy_X(X,Y,Z,f,ty,tz,v0,wx,wy,wz)
%JY_X
%    JY_X = JY_X(X,Y,Z,F,TY,TZ,V0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:14

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t4+t5;
t7 = 1.0./t6;
t8 = sqrt(t6);
t9 = 1.0./t8;
t10 = cos(t8);
t11 = sin(t8);
t12 = t10-1.0;
t13 = t9.*t11.*wx;
t14 = t9.*t11.*wy;
t15 = t9.*t11.*wz;
t16 = t7.*t12.*wx.*wy;
t17 = t7.*t12.*wx.*wz;
t18 = t7.*t12.*wy.*wz;
t21 = t5.*t7.*t12;
t19 = -t16;
t20 = -t18;
t22 = t21+1.0;
t24 = t14+t17;
t23 = Z.*t22;
t25 = X.*t24;
t26 = t24.*v0;
t27 = t13+t20;
t28 = t15+t19;
t29 = -t25;
t30 = Y.*t27;
t31 = f.*t28;
t32 = -t26;
t33 = t31+t32;
t34 = t23+t29+t30+tz;
Jy_X = -(t26-t31)./t34+t24.*1.0./t34.^2.*(Y.*(t27.*v0+f.*(t7.*t12.*(t2+t4)+1.0))+f.*ty+tz.*v0-X.*(t26-t31)-Z.*(f.*(t13+t18)-t22.*v0));
