function Jy_Y = Jy_Y(X,Y,Z,f,ty,tz,v0,wx,wy,wz)
%JY_Y
%    JY_Y = JY_Y(X,Y,Z,F,TY,TZ,V0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:14

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t2+t4;
t7 = t4+t5;
t8 = 1.0./t7;
t9 = sqrt(t7);
t10 = 1.0./t9;
t11 = cos(t9);
t12 = sin(t9);
t13 = t11-1.0;
t14 = t10.*t12.*wx;
t15 = t10.*t12.*wy;
t16 = t8.*t13.*wx.*wz;
t17 = t8.*t13.*wy.*wz;
t19 = t5.*t8.*t13;
t20 = t6.*t8.*t13;
t18 = -t17;
t21 = t19+1.0;
t22 = t20+1.0;
t25 = t15+t16;
t23 = Z.*t21;
t24 = f.*t22;
t26 = X.*t25;
t27 = t14+t18;
t28 = -t26;
t29 = Y.*t27;
t30 = t27.*v0;
t31 = t24+t30;
t32 = t23+t28+t29+tz;
Jy_Y = t31./t32-t27.*1.0./t32.^2.*(Y.*t31+f.*ty+tz.*v0-Z.*(f.*(t14+t17)-t21.*v0)+X.*(f.*(t10.*t12.*wz-t8.*t13.*wx.*wy)-t25.*v0));
