function Jy_Z = Jy_Z(X,Y,Z,f,ty,tz,v0,wx,wy,wz)
%JY_Z
%    JY_Z = JY_Z(X,Y,Z,F,TY,TZ,V0,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jul-2022 14:06:14

t2 = wx.^2;
t3 = wy.^2;
t4 = wz.^2;
t5 = t2+t3;
t6 = t4+t5;
t7 = 1.0./t6;
t8 = sqrt(t6);
t9 = 1.0./t8;
t10 = cos(t8);
t11 = sin(t8);
t12 = t10-1.0;
t13 = t9.*t11.*wx;
t14 = t9.*t11.*wy;
t15 = t7.*t12.*wx.*wz;
t16 = t7.*t12.*wy.*wz;
t18 = t5.*t7.*t12;
t17 = -t16;
t19 = t18+1.0;
t23 = t13+t16;
t24 = t14+t15;
t20 = Z.*t19;
t21 = t19.*v0;
t25 = X.*t24;
t26 = f.*t23;
t27 = t13+t17;
t22 = -t21;
t28 = -t25;
t29 = Y.*t27;
t30 = t22+t26;
t31 = t20+t28+t29+tz;
Jy_Z = (t21-t26)./t31-t19.*1.0./t31.^2.*(Y.*(t27.*v0+f.*(t7.*t12.*(t2+t4)+1.0))+f.*ty+tz.*v0+Z.*(t21-t26)+X.*(f.*(t9.*t11.*wz-t7.*t12.*wx.*wy)-t24.*v0));
